baseURL = 'https://agres.online/'
languageCode = 'en-us'
theme = "hugo-theme-nightfall"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 5

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"
  [[menu.header]]
    name = "whoami"
    weight = 2
    url = "whoami"

[params]
user = "hello"
hostname = "agres.online"

openLinksInNewTab = true

displayDateFormat = "02.01.2006"

# Global metadata display settings
# Each can be overridden in individual post frontmatter
showMetadata = false       # Master switch for all metadata display
showPublishedDate = true  # Show published date on post page
showReadingTime = false    # Show reading time on post page
showTags = true           # Show tags on post page
showAuthors = false        # Show authors on post page
showCategories = false     # Show categories on post page

  [params.author]
    name = "Dominik Agreš"  # Website and RSS feed author
    email = "dominik@agres.online"  # RSS feed email address

[[params.social]]
key = 0
name = "github"
url = "https://github.com/agresdominik"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "linkedIn"
url = "https://www.linkedin.com/in/dominik-agres-4a2765201"
target = "_blank"
aria = "LinkedIn Profile"

[[params.social]]
key = 2
name = "email"
url = "mailto:dominik@agres.online"
aria = "My e-Mail Address"

[[params.social]]
key = 3
name = "pgp-key"
url = "https://agres.online/publickey.asc"
aria = "PGP Key"
